info:
  namespace: shizuart_furnitures

categories:
  vines_props:
    enabled: true
    icon: "shizuart_furnitures:vine_roof_purple"
    name: "Vines Props"
    items:
      - "shizuart_furnitures:vine_cube"
      - "shizuart_furnitures:vine_cube_blue"
      - "shizuart_furnitures:vine_cube_pink"
      - "shizuart_furnitures:vine_cube_purple"
      - "shizuart_furnitures:vine_cube_white"
      - "shizuart_furnitures:vines_windows"
      - "shizuart_furnitures:vines_wall"
      - "shizuart_furnitures:vine_ivy_wall_small"
      - "shizuart_furnitures:vine_ivy_wall_small_blue_flowers"
      - "shizuart_furnitures:vine_ivy_wall_small_pink_flowers"
      - "shizuart_furnitures:vine_ivy_wall_small_purple_flowers"
      - "shizuart_furnitures:vine_ivy_wall_small_white_flowers"
      - "shizuart_furnitures:vine_ivy_wall_small_patch"
      - "shizuart_furnitures:vine_roof"
      - "shizuart_furnitures:vine_roof_blue"
      - "shizuart_furnitures:vine_roof_pink"
      - "shizuart_furnitures:vine_roof_purple"
      - "shizuart_furnitures:vine_roof_white"
      - "shizuart_furnitures:vine_roof_blue_flowers"
      - "shizuart_furnitures:vine_roof_pink_flowers"
      - "shizuart_furnitures:vine_roof_purple_flowers"
      - "shizuart_furnitures:vine_roof_white_flowers"
      - "shizuart_furnitures:vine_roof_small"
      - "shizuart_furnitures:vine_roof_small_blue"
      - "shizuart_furnitures:vine_roof_small_pink"
      - "shizuart_furnitures:vine_roof_small_purple"
      - "shizuart_furnitures:vine_roof_small_white"
      - "shizuart_furnitures:vine_roof_small_blue_flowers"
      - "shizuart_furnitures:vine_roof_small_pink_flowers"
      - "shizuart_furnitures:vine_roof_small_purple_flowers"
      - "shizuart_furnitures:vine_roof_small_white_flowers"
      - "shizuart_furnitures:vine_tree"
      - "shizuart_furnitures:vine_tree_2"
      - "shizuart_furnitures:vine_tree_3"
      - "shizuart_furnitures:vine_tree_4"
      - "shizuart_furnitures:vine_tree_5"
      - "shizuart_furnitures:vine_tree_6"
      - "shizuart_furnitures:vine_tree_long"
      - "shizuart_furnitures:vine_tree_long_blue_flowers"
      - "shizuart_furnitures:vine_tree_long_pink_flowers"
      - "shizuart_furnitures:vine_tree_long_purple_flowers"
      - "shizuart_furnitures:vine_tree_long_white_flowers"
      - "shizuart_furnitures:vine_wall"
      - "shizuart_furnitures:vine_wall_blue_flowers"
      - "shizuart_furnitures:vine_wall_pink_flowers"
      - "shizuart_furnitures:vine_wall_purple_flowers"
      - "shizuart_furnitures:vine_wall_white_flowers"
      - "shizuart_furnitures:vines_wall_top"
      - "shizuart_furnitures:vine_small_wall"
      - "shizuart_furnitures:vines_wall_big"

#2fd43ab3a82e860ae39c70963cbf643a